
exclude: '^docs/conf.py'

repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: check-toml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=no']
  - id: flake8
    args: [
      '--max-line-length=88',
      '--ignore=W503,E265,E501,E741,B007,F811,F821,F841,F401,PD011,PD002,E800,E402,C408']  # default of Black
    additional_dependencies:
      - flake8-bugbear
      - flake8-comprehensions
      - flake8-debugger
      - flake8-eradicate
      - flake8-executable
      - flake8-mock
      - flake8-mutable
      - flake8
      - pandas-vet  # not worthy if you are not using pandas (e.g. PD011)

- repo: https://github.com/PyCQA/bandit
  rev: 1.6.2
  hooks:
    - id: bandit
      args: [--exclude, tests/]

- repo: https://github.com/ambv/black
  rev: 19.10b0
  hooks:
    - id: black
      args: [--safe]
      language_version: python3.7

- repo: https://github.com/asottile/seed-isort-config
  rev: v1.9.4
  hooks:
    - id: seed-isort-config
      args: [--application-directories, '.']

      #- repo: https://github.com/pre-commit/mirrors-isort
      #  rev: v4.3.21
      #  hooks:
      #    - id: isort

- repo: https://github.com/asottile/pyupgrade
  rev: v1.26.0
  hooks:
    - id: pyupgrade
